package plugins.org.craftercms.aiassistant.spi.tool

/**
 * JSON Schema strings for built-in tools on the chat-completions tools-loop wire ({@link plugins.org.craftercms.aiassistant.spi.tool.StudioAiOrchestrationTool#inputSchemaJson()}).
 */
final class StudioAiToolSchemas {

  /**
   * Private constructor; not for direct use.
   */
private StudioAiToolSchemas() {}

  static final String GET_CONTENT =
    '{"type":"object","properties":{"siteId":{"type":"string","description":"Studio site id"},"path":{"type":"string","description":"Repository path starting with /"},"contentPath":{"type":"string","description":"Same as path; use whichever matches your context (e.g. after update_content)."},"commitId":{"type":"string","description":"Git commit id or ref to read (optional). Omit or use HEAD for current sandbox file; set only when comparing or inspecting history."}},"required":["siteId"]}'

  static final String CONTENT_EXISTS =
    '{"type":"object","properties":{"siteId":{"type":"string","description":"Studio site id"},"path":{"type":"string","description":"Repository path starting with /"},"contentPath":{"type":"string","description":"Same as path"},"paths":{"type":"array","items":{"type":"string"},"description":"Optional — check multiple paths in one call (each must start with /)."}},"required":["siteId"]}'

  static final String GET_CONTENT_TYPE =
    '{"type":"object","properties":{"siteId":{"type":"string"},"contentPath":{"type":"string","description":"Repository path to page/component XML (e.g. /site/website/index.xml). Preferred: server reads exact <content-type> from this file — avoids guessing /page/index from filename."},"contentTypeId":{"type":"string","description":"Exact /page/... or /component/... from the item XML <content-type> element only. Never infer from path (index.xml is NOT /page/index)."}},"required":["siteId"]}'

  static final String LIST_STUDIO_CONTENT_TYPES =
    '{"type":"object","properties":{"siteId":{"type":"string","description":"Studio site id"},"searchable":{"type":"boolean","description":"If true, pass searchable=true to Studio getAllContentTypes when listing all types (site-dependent). Default false."},"contentPath":{"type":"string","description":"Optional repository path (e.g. open preview item or target folder). When set, lists content types **allowed** for creating items under that path’s folder (via Studio getAllowedContentTypesForPath)."}},"required":["siteId"]}'

  static final String GET_CONTENT_VERSION_HISTORY =
    '{"type":"object","properties":{"siteId":{"type":"string","description":"Studio site id"},"path":{"type":"string","description":"Repository path starting with /"},"contentPath":{"type":"string","description":"Same as path"}},"required":["siteId"]}'

  static final String GET_PREVIEW_HTML =
    '{"type":"object","properties":{"url":{"type":"string","description":"Absolute http(s) URL of the preview page to fetch (e.g. current preview URL from authoring context)."},"previewUrl":{"type":"string","description":"Alias for url."},"previewToken":{"type":"string","description":"Value of the Studio crafterPreview cookie (often starts with CCE-V1). Omit if the chat request already sent previewToken from the UI."},"siteId":{"type":"string","description":"Optional — when the URL has no crafterSite= query param, it is appended from this value or the active site."}},"required":[]}'

  static final String FETCH_HTTP_URL =
    '{"type":"object","properties":{"url":{"type":"string","description":"Absolute http(s) URL to GET (reference HTML/CSS/JSON/text). Private IPs, loopback, and metadata endpoints are blocked; each redirect target is re-validated."},"maxChars":{"type":"integer","description":"Optional cap on returned body size; still bounded by Studio JVM aiassistant.httpFetch.maxChars (default 400000)."}},"required":["url"]}'

  static final String POST_HTTP_URL =
    '{"type":"object","properties":{"url":{"type":"string","description":"Absolute http(s) URL to POST. Same SSRF policy as FetchHttpUrl (public http(s) only)."},"postType":{"type":"string","description":"json (application/json body) or form (application/x-www-form-urlencoded). Default json."},"payload":{"description":"JSON: object/array (serialized) or JSON string. Form: flat map of field names to string/number/boolean values, or a raw application/x-www-form-urlencoded string."},"headers":{"type":"object","description":"Optional extra request headers (string values). Host, Content-Length, and Connection are ignored."},"maxChars":{"type":"integer","description":"Optional cap on response body size; bounded by JVM aiassistant.httpFetch.maxChars."}},"required":["url","payload"]}'

  static final String SLACK_POST_MESSAGE =
    '{"type":"object","properties":{"channel":{"type":"string","description":"Slack channel ID (C…) or name (#general). Required unless site defaultChannel is set in tools.json."},"secretKey":{"type":"string","description":"Optional secrets.json key for this workspace bot token (default slack_bot_token). Use when the site stores multiple Slack tokens."},"text":{"type":"string","description":"Message text (mrkdwn). Use with or without blocks."},"message":{"type":"string","description":"Alias for text."},"blocks":{"description":"Block Kit blocks (array or JSON string)."},"attachments":{"description":"Legacy attachments (array or JSON string)."},"threadTs":{"type":"string","description":"Parent message ts to reply in a thread."},"username":{"type":"string","description":"Optional bot display name for this message."},"iconEmoji":{"type":"string","description":"Emoji icon for this message, e.g. :rocket:"},"iconUrl":{"type":"string","description":"Image URL for message icon."},"mrkdwn":{"type":"boolean","description":"Enable Slack mrkdwn formatting (default true)."},"unfurlLinks":{"type":"boolean"},"unfurlMedia":{"type":"boolean"},"replyBroadcast":{"type":"boolean","description":"Also post thread reply to channel."},"linkNames":{"type":"boolean"},"metadata":{"type":"object","description":"Slack message metadata object."}},"required":[]}'

  static final String WEB_SEARCH =
    '{"type":"object","properties":{"query":{"type":"string","description":"Search query (news, current events, or open-web facts)."},"q":{"type":"string","description":"Alias for query."},"maxResults":{"type":"integer","description":"Max results (1–15, default 8)."}},"required":["query"]}'

  static final String SERP_API_WEB_SEARCH =
    '{"type":"object","properties":{"query":{"type":"string","description":"Search query (news, current events, or open-web facts)."},"q":{"type":"string","description":"Alias for query."},"maxResults":{"type":"integer","description":"Max organic results (1–20; site defaults apply)."},"engine":{"type":"string","description":"SerpAPI engine (default google from site tools.json)."},"googleDomain":{"type":"string","description":"Google domain, e.g. google.com."},"gl":{"type":"string","description":"Country code for results, e.g. us."},"hl":{"type":"string","description":"Interface language, e.g. en."},"location":{"type":"string","description":"Geo location string for Google, e.g. United States."},"num":{"type":"integer","description":"Result count override (SerpAPI num)."},"start":{"type":"integer","description":"Pagination offset (SerpAPI start)."},"device":{"type":"string","description":"desktop | tablet | mobile."},"safe":{"type":"string","description":"Safe search: active | off."},"tbm":{"type":"string","description":"Google vertical, e.g. nws for news."},"tbs":{"type":"string","description":"Time filter, e.g. qdr:d for past day."}},"required":["query"]}'

  static final String CONSULT_CRAFTERQ =
    '{"type":"object","properties":{"agentId":{"type":"string","description":"CrafterQ agent UUID, or chat.crafterq.ai URL whose last path segment is the agent id."},"prompt":{"type":"string","description":"Instructions or question for the CrafterQ agent. Provide prompt or question (at least one required)."},"question":{"type":"string","description":"Alias for prompt."},"draft":{"type":"string","description":"Optional long text appended after prompt (e.g. $slackOutbound.draft in recipes)."},"context":{"type":"string","description":"Alias for draft."},"chatUser":{"type":"string","description":"Optional override for X-CrafterQ-Chat-User; default mints via GET /v1/agents/{agentId}/chat_config."}},"required":["agentId"]}'

  static final String RESEARCH_SITE_CONTENT =
    '{"type":"object","properties":{"siteId":{"type":"string","description":"Studio site id"},"query":{"type":"string","description":"Keywords to search indexed site pages and components (authoring OpenSearch)."},"q":{"type":"string","description":"Alias for query."},"maxSearchHits":{"type":"integer","description":"Max OpenSearch hits (1–30, default JVM aiassistant.siteContentResearch.maxSearchHits)."},"maxFetchItems":{"type":"integer","description":"How many top hits to load full XML excerpts for (0–10, default aiassistant.siteContentResearch.maxFetchItems)."},"pathPrefix":{"type":"string","description":"Optional localId prefix filter (default /site/)."}},"required":["siteId","query"]}'

  static final String WRITE_CONTENT =
    '{"type":"object","properties":{"siteId":{"type":"string"},"path":{"type":"string","description":"Repository path starting with /"},"contentPath":{"type":"string","description":"Same as path; use either."},"contentXml":{"type":"string","description":"Complete file body. For /site/.../*.xml items: full <page> or <component> document preserving existing field element names from the content type; never replace with an unrelated XML schema."},"unlock":{"type":"string","description":"true or false"}},"required":["siteId","contentXml"]}'

  static final String LIST_PAGES =
    '{"type":"object","properties":{"siteId":{"type":"string"},"size":{"type":"integer","description":"max items, default 1000"}},"required":["siteId"]}'

  static final String LIST_CONTENT_DEPENDENCY_SCOPE =
    '{"type":"object","properties":{"siteId":{"type":"string"},"contentPath":{"type":"string","description":"Root page or component XML under /site/... ending in .xml"},"path":{"type":"string","description":"Alias for contentPath"},"chunkSize":{"type":"integer","description":"Paths per batch for GetContent/WriteContent rounds (default 1 — one item at a time; max 50)"},"maxItems":{"type":"integer","description":"Optional max items in scope (default 300, cap 2000)"},"maxDepth":{"type":"integer","description":"Optional max reference depth from root (default 40, cap 100)"}},"required":["siteId"]}'

  static final String CRAFTERIZING_PLAYBOOK =
    '{"type":"object","properties":{"topic":{"type":"string","description":"Optional focus keyword for future use; full playbook is returned regardless."}}}'

  static final String GENERATE_PLACEHOLDER_IMAGE =
    '{"type":"object","properties":{"width":{"type":"integer","description":"Placeholder width in pixels (default 150; min 16, max 4096). Alias: w."},"height":{"type":"integer","description":"Placeholder height in pixels (default 150; min 16, max 4096). Alias: h."},"w":{"type":"integer","description":"Alias for width."},"h":{"type":"integer","description":"Alias for height."}},"required":[]}'

  static final String CMS_LOOSE =
    '{"type":"object","properties":{"siteId":{"type":"string"},"site_id":{"type":"string"},"path":{"type":"string"},"contentPath":{"type":"string"},"paths":{"type":"array","items":{"type":"string"},"description":"Repository paths for publishScope=paths (one deploy)"},"contentPaths":{"type":"array","items":{"type":"string"},"description":"Alias for paths"},"publishScope":{"type":"string","description":"item | paths | bulk | all"},"publishMode":{"type":"string","description":"Alias for publishScope"},"publishEntireSite":{"type":"boolean"},"publishAll":{"type":"boolean"},"publishEverything":{"type":"boolean"},"bulkRootPath":{"type":"string","description":"Subtree root for publishScope=bulk (default /site)"},"bulkPath":{"type":"string","description":"Alias for bulkRootPath"},"submissionComment":{"type":"string"},"comment":{"type":"string","description":"Alias for submissionComment"},"templatePath":{"type":"string"},"contentType":{"type":"string"},"contentTypeId":{"type":"string"},"instructions":{"type":"string"},"date":{"type":"string"},"publishingTarget":{"type":"string"},"revertType":{"type":"string"},"version":{"type":"string","description":"Studio ItemVersion versionNumber from GetContentVersionHistory"},"revertToPrevious":{"type":"boolean","description":"If true, revert to the immediate prior revertible version (no version string needed)"},"revertToInitial":{"type":"boolean","description":"If true, revert to the oldest revertible version in history (e.g. initial commit)"},"contentContains":{"type":"array","items":{"type":"string"},"description":"Distinct phrases; server picks newest history version whose body contains all of them"},"contentFieldId":{"type":"string","description":"Optional element id from GetContentTypeFormDefinition when scoping contentContains to one field"}}}'

  static final String QUERY_EXPERT_GUIDANCE =
    '{"type":"object","properties":{"skillId":{"type":"string","description":"Expert skill id from the system message expert skills table (es_ prefix)."},"query":{"type":"string","description":"Question to retrieve relevant markdown chunks for."},"topK":{"type":"integer","description":"Max chunks (1–20, default 8)."}},"required":["skillId","query"]}'

  static final String GENERATE_IMAGE =
    '{"type":"object","additionalProperties":false,"properties":{"prompt":{"type":"string","description":"Description of the image to generate"},"size":{"type":"string","enum":["auto","1024x1024","1024x1536","1536x1024"],"description":"Optional image size preset (built-in images API when active): auto, 1024x1024, 1024x1536, 1536x1024 — omit unless the author asked for aspect ratio. Server coerces invalid values (e.g. 1024x768 → nearest supported)."},"quality":{"type":"string","description":"Optional quality: low, medium, high, auto"},"model":{"type":"string","description":"Optional override of configured imageModel. Do not pass response_format when the images API rejects it."}},"required":["prompt"]}'

  static final String GENERATE_TEXT_NO_TOOLS =
    '{"type":"object","properties":{"userPrompt":{"type":"string","description":"Full user/task text for the inner model (what to write, format, constraints)."},"prompt":{"type":"string","description":"Alias for userPrompt."},"systemInstructions":{"type":"string","description":"Optional system message for this inner call only (role, output shape, tone)."},"system":{"type":"string","description":"Alias for systemInstructions."},"maxOutTokens":{"type":"integer","description":"Max completion tokens for this inner call (256–8192; server may clamp per model)."},"model":{"type":"string","description":"Optional chat model id for this inner call only; default matches the agent chat model family."},"llmModel":{"type":"string","description":"Alias for model."},"readTimeoutMs":{"type":"integer","description":"HTTP read timeout ms (60000–600000)."}},"required":[]}'

  static final String TRANSFORM_CONTENT_SUBGRAPH =
    '{"type":"object","properties":{"siteId":{"type":"string"},"contentPath":{"type":"string","description":"Root page or component XML under /site/... ending in .xml"},"path":{"type":"string","description":"Alias for contentPath"},"instructions":{"type":"string","description":"Task for the worker model (e.g. translate all author-visible copy to Arabic ar-SA; preserve XML structure)"},"writeResults":{"type":"boolean","description":"If true (default), WriteContent each document after a valid LLM bundle"},"maxItems":{"type":"integer","description":"Max documents in walk (default 300, cap 2000)"},"maxDepth":{"type":"integer","description":"Max reference depth (default 40, cap 100)"},"unlock":{"type":"string","description":"Unlock flag for WriteContent (default true)"},"llmModel":{"type":"string","description":"Chat model for the bundled inner completion only. Omit to use a smaller model in the same family as main chat. Pass explicitly to override. Alias: model"},"readTimeoutMs":{"type":"integer","description":"HTTP read timeout ms for the inner call (default 600000)"}},"required":["siteId","instructions"]}'

  static final String TRANSLATE_CONTENT_ITEM =
    '{"type":"object","properties":{"siteId":{"type":"string"},"contentPath":{"type":"string","description":"One page or component XML under /site/... ending in .xml"},"path":{"type":"string","description":"Alias for contentPath"},"instructions":{"type":"string","description":"Same task for every item when translating a page tree (e.g. translate author-visible copy to Arabic ar-SA; preserve XML)"},"writeResults":{"type":"boolean","description":"If true (default), WriteContent after a valid LLM bundle"},"unlock":{"type":"string","description":"Unlock flag for WriteContent (default true)"},"llmModel":{"type":"string","description":"Chat model for this item only (inner completion). Omit for server default smaller model in the same family. Alias: model"},"readTimeoutMs":{"type":"integer","description":"HTTP read timeout ms for the inner call (default 600000)"}},"required":["siteId","instructions"]}'

  static final String TRANSLATE_CONTENT_BATCH =
    '{"type":"object","properties":{"siteId":{"type":"string"},"instructions":{"type":"string","description":"Same instruction for every path (e.g. translate author-visible copy to French fr-FR)"},"paths":{"type":"array","items":{"type":"string"},"description":"List of /site/.../*.xml paths"},"contentPaths":{"type":"array","items":{"type":"string"},"description":"Alias for paths"},"pathChunks":{"type":"array","description":"Optional: **pathChunks** from ListContentDependencyScope — same shape as that tool (outer array of chunks; each chunk is an array of path strings). Server flattens to paths.","items":{"type":"array","items":{"type":"string","description":"/site/.../*.xml repository path"}}},"maxConcurrency":{"type":"integer","description":"Parallel workers for this batch only (default from agent agents.json translateBatchConcurrency, else 25; hard cap 64)"},"writeResults":{"type":"boolean"},"unlock":{"type":"string"},"llmModel":{"type":"string"},"model":{"type":"string"},"readTimeoutMs":{"type":"integer"}},"required":["siteId","instructions"]}'

  static final String INVOKE_SITE_USER_TOOL =
    '{"type":"object","properties":{"toolId":{"type":"string","description":"Registered id from the site registry.json tools[] array."},"args":{"type":"object","description":"Optional map passed to the script as binding variable args.","additionalProperties":true}},"required":["toolId"]}'
}
